name: Issue new release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "!*"

jobs:
  release:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ 'ubuntu-20.04' ]
        go: [ '1.18' ]
    runs-on: ${{ matrix.os }}
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: ${{ matrix.go }}

      - name: Install tools
        run: |
          make install-tools

      - name: Vet
        run: |
          make vet

      - name: Lint
        run: |
          make lint-pipeline

      - name: Run GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make release
